apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: {{ .Chart.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/api-configmap.yaml") . | sha256sum }}
    spec:
      {{- if or (.Values.global.imagePullSecrets) (and (not (empty .Values.appco)) (not (empty .Values.appco.pullSecret))) }}
      imagePullSecrets:
      {{- with .Values.global.imagePullSecrets }}
      {{- range $ps := . }}
      - name: {{ $ps }}
      {{- end }}
      {{- end }}
      {{- if and (not (empty .Values.appco)) (not (empty .Values.appco.pullSecret)) }}
      - name: {{ .Values.appco.pullSecret }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-api
          image: {{ .Values.api.image }}
          command: ["node", "/app/server.js"]
          ports:
            - containerPort: 3000
          env:
            - name: EXPECTED_IMAGE_REPOSITORY
              value: {{ .Values.api.expectedImageRepository | quote }}
            - name: ACTUAL_IMAGE
              value: {{ .Values.ui.image | quote }}
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: code
              mountPath: /app/server.js
              subPath: server.js
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}

      volumes:
        - name: code
          configMap:
            name: {{ .Release.Name }}-api-code
