apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ if .Values.ui.exposeLoadBalancer }}LoadBalancer{{ else }}{{ .Values.ui.service.type }}{{ end }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ui
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
