global:
  imagePullSecrets: []
# Pull the latest nginx image from Docker Hub
nginx:
  image:
    registry: ''
    repository: nginx
    tag: latest

replicas: 1
ingress:
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  host: "satellite-uplink.local"
  tls:
    secretName: wildcard-tls
k6:
  image:
    registry: ''
    repository: grafana/k6
    tag: latest
    pullPolicy: Always
  loadTest:
    duration: "60m"
    vus: 10
