global:
  imageRegistry: ""

airlock:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: suse-technical-marketing/mission-control-backend
    tag: main
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

gravity:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: suse-technical-marketing/mission-control-backend
    tag: main
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

lifeSupport:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: suse-technical-marketing/mission-control-backend
    tag: main
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

powerCore:
  replicaCount: 2
  image:
    registry: ghcr.io
    repository: suse-technical-marketing/mission-control-backend
    tag: main
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  instabilityFactor: "0.3"

frontend:
  replicaCount: 1
  image:
    registry: ghcr.io
    repository: suse-technical-marketing/mission-control-frontend
    tag: main
    pullPolicy: Always
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

ingress:
  enabled: true
  ingressClassName: nginx
  host: mission-control.lab.geeko.me
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: mission-control-tls

env:
  OTLP_ENDPOINT: "http://otel-collector.lab.geeko.me:4317"
  API_BASE_URL: "https://mission-control.lab.geeko.me"
  REDIS_HOST: "redis-headless.redis.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""

