global:
  imagePullSecrets: []
nginx:
  # Pull the latest nginx image from Docker Hub
  image: nginx:latest
  replicas: 1
  ingress:
    className: "traefik"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    host: "deep-space-network.local"
    tls:
      secretName: wildcard-tls
k6:
  loadTest:
    duration: "60m"
    vus: 10
