apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-k6-loadgen
  labels:
    {{- include "sattrack.labels" (dict "app" "k6-loadgen" "root" .) | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6-loadgen
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: k6-loadgen
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/k6-loadgen-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: k6
          image: grafana/k6:latest
          command:
            - k6
            - run
            - /scripts/script.js
          env:
            - name: TARGET_URL
              value: "http://{{ .Release.Name }}-sattrack-ui:80"
            - name: RPS
              value: {{ .Values.k6.rps | quote }}
          volumeMounts:
            - name: script
              mountPath: /scripts/script.js
              subPath: script.js
          resources:
            requests: { cpu: 50m,  memory: 64Mi  }
            limits:   { cpu: 200m, memory: 128Mi }
      volumes:
        - name: script
          configMap:
            name: {{ .Release.Name }}-k6-script
