apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sat-receiver
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: sat-receiver
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: sat-receiver
  ports:
    - port: {{ .Values.satReceiver.port }}
      targetPort: {{ .Values.satReceiver.port }}
      name: http
