apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-telemetry-store
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: telemetry-store
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: telemetry-store
  ports:
    - port: {{ .Values.telemetryStore.port }}
      targetPort: {{ .Values.telemetryStore.port }}
      name: http