{{- if .Values.airlock.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: airlock-service
spec:
  selector:
    app: airlock
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
{{- end }}