apiVersion: v1
kind: Service
metadata:
  name: power-core-headless-service
spec:
  selector:
    app: power-core
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  clusterIP: None
